### PR TITLE
Bug/user status update

### LINKED ISSUE #13: Online Status of User not updated on Login
Details:
When a user first logs in and opens a chat, the chat user is viewed as offline even if the user is actually online.

Steps to recreate: 
Log in with an account in one device, say account A.
Login with account B on another device.
Open the chat with A while logged in with B.
You will see that A is offline, while A is actually online on the other device.

Would Like someone to fix it.

### PR DESCRIPTION
**Pull request by ozair-dev**
Update user's online status on login and logout

Fixed #13

### CODE REVIEW

**Comment by ThaHobbyist** [comment]
Still the same bug exists. The status is not getting updated when the user is at the home screen, without any chat opened

**Comment by ozair-dev** [comment]
So you want to show user status as **offline** when user is at home screen without a chat open? That's kinda weird tho.

The vercal preview here is not showing my changes properly because of some cors issue.
You have provided https://h-chat.vercel.app as the origin in the cors options but it is now getting https://h-chat-git-fork-ozair-dev-bug-user-status-update-thahobbyist.vercel.app as the origin, so It won't show my changes unless you push the changes to production.
Or simply, you should run my code locally, hopefully you will see everythinhg working correctly.

**Comment by ThaHobbyist** [comment]
I want the status to be online when user is even in the home page without
chat open, but currently in your pr, it is the opposite

**Comment by ozair-dev** [comment]
Did you run changes on your machine?

**Comment by ThaHobbyist** [comment]
I deployed it on vercel and ran it

**Comment by ozair-dev** [comment]
Means you didn't read my comment completely

**Pull request closed without merging**
