### PR TITLE
Bug/user status update

### LINKED ISSUE #13: Online Status of User not updated on Login
Details:
When a user first logs in and opens a chat, the chat user is viewed as offline even if the user is actually online.

Steps to recreate: 
Log in with an account in one device, say account A.
Login with account B on another device.
Open the chat with A while logged in with B.
You will see that A is offline, while A is actually online on the other device.

Would Like someone to fix it.

### PR DESCRIPTION
**Pull request by ozair-dev**
Update user status when user goes  **online** or **offline**

Fixes #13

### CODE REVIEW

**Comment by ozair-dev** [comment]
@ThaHobbyist check...

**Comment by ThaHobbyist** [comment]
@ozair-dev There is another bug, the Online status does not change when the second users logs out.

**Comment by ozair-dev** [comment]
can u please authorize this commit so that I can see the deployed version on vercel

**Comment by ozair-dev** [comment]
For some reason, this deployement is not showing the changes I made.
How did you test my changes? Did you run my changes on your machine locally?

I'll look into it later. Maybe tomorrow.

**Comment by ThaHobbyist** [comment]
yes I ran the changes locally

**Comment by ozair-dev** [comment]
@ThaHobbyist check now

**Comment by ozair-dev** [comment]
u there?

**Comment by ThaHobbyist** [comment]
Sorry I was a bit busy in the last few days. Will check the pr today after classes

**Comment by ThaHobbyist** [comment]
The status is not changed realtime when the user logs out @ozair-dev 
The status is updated when the 2nd user closes the window, but not when he logs out

**Comment by ThaHobbyist** [comment]
I am closing the pull request as there are no updates given

**Comment by ozair-dev** [comment]
I forgot about it. You could've reminded me of this instead of closing it tho.
Should I open a new PR with the new fix?

**Comment by ThaHobbyist** [comment]
Yea sure, you can open a new pr

**Pull request closed without merging**
